---
# App tgz file name
app_package: '{{ app_name }}-{{ app_version }}{{ app_classifier }}.tar.gz'

# TODO dirty hack for now!!
app_url: 'https://oss.sonatype.org/content/repositories/snapshots/io/fabric8/quickstarts/cdi-camel/2.2.98-SNAPSHOT/cdi-camel-2.2.98-20160215.112841-2-app.tar.gz'
